<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Conversation extends Model
{
    use \App\Http\Controllers\Traits\Image;

    protected $fillable = [
        'category_id', 'conversation_en', 'record_en', 'conversation_es', 'record_es', 'image', 'eg_link', 'visible'
    ];

    public function category()
    {
        return $this->belongsTo('App\Models\Category', 'category_id', 'id')->with('parent');
    }

    protected static function boot()
    {
        static::deleting(function ($model) {
            $model->deleteAudios();

            $model->getImagePath('conversations', false, function ($image) {
                unlink($image);
            });

            $model->getImagePath('conversations', true, function ($image) {
                unlink($image);
            });
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }
}
