<?php

namespace App\Models;

use App\Studied;
use Illuminate\Database\Eloquent\Model;

class Exercise extends Model
{
    use \App\Http\Controllers\Traits\Image;

    protected $fillable = [
        'category_id', 'type', 'words', 'image', 'title', 'record_en', 'record_es', 'exercise_en', 'exercise_es', 'visible'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id')->with('parent');
    }

    protected static function boot()
    {
        static::deleting(function ($model) {
            $model->deleteAudios();

            $model->getImagePath('phrases', false, function ($image) {
                unlink($image);
            });

            $model->getImagePath('phrases', true, function ($image) {
                unlink($image);
            });

            $studied = Studied::where(['type' => 'exercises', 'id' => $model->id])->find();

            if ($studied) {
                $studied->delete();
            }
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }
}
