<?php

namespace App\Models;

use App\ItemState;
use App\Studied;
use Illuminate\Database\Eloquent\Model;

class Phrase extends Model
{
    use \App\Http\Controllers\Traits\Image;

    protected $fillable = [
        'category_id', 'phrase_en', 'record_en', 'phrase_es', 'record_es', 'image', 'eg_link', 'visible'
    ];

    public function category()
    {
        return $this->belongsTo('App\Models\Category', 'category_id', 'id')->with('parent');
    }

    protected static function boot()
    {
        static::deleting(function ($model) {
            $model->deleteAudios();

            $model->getImagePath('phrases', false, function ($image) {
                unlink($image);
            });

            $model->getImagePath('phrases', true, function ($image) {
                unlink($image);
            });

            $studied = Studied::where(['type' => 'phrases', 'id' => $model->id, 'user_id' => auth()->id()])->find();

            if ($studied) {
                $studied->delete();
            }

            $itemState = ItemState::where(['type' => 'phrases', 'id' => $model->id, 'user_id' => auth()->id()])->find();

            if ($itemState) {
                $itemState->delete();
            }
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }
}
