<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Verb extends Model
{
    use \App\Http\Controllers\Traits\Image;

    protected $fillable = [
        'category_id', 'verb_en', 'record_en', 'verb_es', 'record_es', 'image', 'eg_link', 'visible'
    ];

    public function category()
    {
        return $this->belongsTo('App\Models\Category', 'category_id', 'id')->with('parent');
    }

    protected static function boot()
    {
        static::deleting(function ($model) {
            $model->deleteAudios();

            $model->getImagePath('verbs', false, function ($image) {
                unlink($image);
            });

            $model->getImagePath('verbs', true, function ($image) {
                unlink($image);
            });
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }
}
